version: '2'

services:

    php:
        image: atillay/craftcms3-php
        links:
            - mysql
        volumes:
            - ".:/var/www"

    mysql:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=StrongPassword
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        volumes:
            - "./docker/volumes/mysql:/var/lib/mysql"

    nginx:
        build:
            context: ./docker/nginx
        ports:
            - "${CRAFT_PORT}:80"
        links:
            - php
        volumes:
            - "./log:/var/log/nginx"
        volumes_from:
            - php

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "${PMA_PORT}:80"
        links:
            - mysql
        environment:
            - PMA_HOST=${DB_SERVER}

    maildev:
        image: djfarrelly/maildev
        ports:
            - "${MAILDEV_PORT}:80"
