version: '3'

services:

    php:
        image: atillay/craftcms3-php
        volumes:
            - .:/var/www

    nginx:
        build:
            context: ./docker/nginx
        ports:
            - ${CRAFT_PORT}:80
        volumes:
            - ./log:/var/log/nginx
            - ./web:/var/www/web

    mysql:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=StrongPassword
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./docker/volumes/mysql:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - ${PMA_PORT}:80
        environment:
            - PMA_HOST=${DB_SERVER}

    maildev:
        image: djfarrelly/maildev
        ports:
            - ${MAILDEV_PORT}:80
